### ISSUE TITLE
Bottom Menu Bar

### ISSUE THREAD

**Issue by dvdkwei** [copybarra/chat-client#16]
Als Dev möchte ich unter dem _Chat Container_ einen _Bottom-Menu Component_ erstellen, damit der User die Möglichkeiten hat, einen neuen Chat anzulegen, eine neue Gruppe zu erstellen und die Einstellungen zu der App aufzumachen.

![menu-bar](https://user-images.githubusercontent.com/81156524/193221577-45ce6653-b3db-42d6-bc8a-d91bd4d0e486.png)

**Comment by janwalenda** [comment]
Wieso hat nur der Butten links dünne Linien?

**Comment by dvdkwei** [comment]
> Wieso hat nur der Butten links dünne Linien?

gute anmerkung, schreib bitte ein bug ticket dafür 😜
