### ISSUE TITLE
NextJS?

### ISSUE THREAD

**Issue by janwalenda** [copybarra/chat-client#22]
Wollen wir NextJS in unser projekt integrieren?
Vorteile:
- SSG
- Kürzere Ladezeiten
- SEO

Nachteile:
- Alles muss umgeschrieben werden
- Konfiguration komplizierter

**Comment by bvoigtlaender** [comment]
**nein**

**Comment by dvdkwei** [comment]
**bread 🍞**

**Comment by janwalenda** [comment]
![image](https://user-images.githubusercontent.com/51045811/194334811-fd60308a-f7e3-4105-af07-443b5c2ee295.png)
