### ISSUE TITLE
Server erstellen auf AWS Amplify

### ISSUE THREAD

**Issue by bvoigtlaender** [copybarra/chat-client#3]

**Comment by bvoigtlaender** [comment]
Vielleicht reicht auch ein S3 Server. Das müsste sich jemand genauer anschauen.

**Comment by bvoigtlaender** [comment]
Oder Netlify oder Vercel

**Comment by janwalenda** [comment]
Jans Server? oder ist das nicht mehr aktuell?

**Comment by dvdkwei** [comment]
Der Server ist doch schon da, oder? 🤔

**Comment by bvoigtlaender** [comment]
Ja, wird jetzt auf Vercel gehostet #serverless #jamstack

**Comment by janwalenda** [comment]
☠️☠️☠️
